### ISSUE TITLE
v0.2 put ENV variables into service module types

### ISSUE THREAD

**Issue by kacole2** [emccode/rexray#38] opened 2015-09-11 02:20 UTC
rexray still functions in v0.2 just as it used to in v0.1x when ENV variables were used for configuration. I can still declare ENV variables and rexray still creates volumes. However, the ENV variables are not populated in the configuration output with `rexray service module types`.

**Comment by akutz** [comment] 2015-09-11 05:08
Hi @kacole2,

It appears this is a duplicate of #39 and so I'm closing this ticket.

**Closed by akutz** 2015-09-11 05:08 UTC
