### ISSUE TITLE
cannot install rexray from bintray file downloads

### ISSUE THREAD

**Issue by kacole2** [emccode/rexray#55] opened 2015-09-15 03:53 UTC
here are my steps to recreate

#### wget
Download the file using wget, tar, move, +x, install
```
$ wget https://bintray.com/artifact/download/akutz/generic/rexray-linux_amd64-0.2.0-rc2%2B18.tar.gz
$ tar xzfv rexray-linux_amd64-0.2.0-rc2+18.tar.gz
$ sudo mv rexray /bin/rexray
$ sudo chmod +x /bin/rexray
$ sudo rexray service install
update-rc.d: /etc/init.d/rexray: file does not exist
FATA[0000] installation error exit status 1
```

#### curl
Download the file using wget, tar, move, +x, install
```
$ curl -LOk https://bintray.com/artifact/download/akutz/generic/rexray-linux_amd64-0.2.0-rc2%2B18.tar.gz
$ tar xzfv rexray-linux_amd64-0.2.0-rc2+18.tar.gz
$ sudo mv rexray /bin/rexray
$ sudo chmod +x /bin/rexray
$ sudo rexray service install
ERRO[0000] error reading configuration file(s) from default path(s)  error=open : no such file or directory global=/etc/rexray/config.yaml user=/root/.rexray/config.yaml
ERRO[0000] error reading configuration file(s) from default path(s)  error=open : no such file or directory global=/etc/rexray/config.yaml user=/root/.rexray/config.yaml
ERRO[0000] error reading configuration file(s) from default path(s)  error=open : no such file or directory global=/etc/rexray/config.yaml user=/root/.rexray/config.yaml
panic: open /root/.rexray/usage.template: permission denied

goroutine 1 [running]:
github.com/emccode/rexray/rexray/commands.initUsageTemplates()
	/home/travis/gopath/src/github.com/emccode/rexray/rexray/commands/usage.go:25 +0x38e
github.com/emccode/rexray/rexray/commands.init.1()
	/home/travis/gopath/src/github.com/emccode/rexray/rexray/commands/rexraycli.go:113 +0x40
github.com/emccode/rexray/rexray/commands.init()
	/home/travis/gopath/src/github.com/emccode/rexray/rexray/commands/usage.go:139 +0x4c9
main.init()
	/home/travis/gopath/src/github.com/emccode/rexray/rexray/rexray.go:28 +0x40

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 6 [runnable]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:20
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

**Comment by clintonskitson** [comment] 2015-09-15 04:21
@kacole2 what is the linux distro and version?

**Comment by kacole2** [comment] 2015-09-15 04:25
Ubuntu 14.04

**Comment by akutz** [comment] 2015-09-15 05:10
@kacole2 Your system is FUBAR. Works fine here on same distro.

```
[0]akutz@ubuntu:~$ /bin/rexray version
SemVer: 0.2.0-rc2+20
Binary: linux_amd64
Branch: master
Commit: f23b8217b38e9461cf795e97463c4b006182aa5c
Formed: Mon, 14 Sep 2015 23:59:27 CDT

[0]akutz@ubuntu:~$ uname -a
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[0]akutz@ubuntu:~$ 
```

Here's the process I used:

```
[0]akutz@ubuntu:~$ wget https://bintray.com/artifact/download/akutz/generic/rexray-linux_amd64-0.2.0-rc2%2B20.tar.gz
--2015-09-15 00:02:47--  https://bintray.com/artifact/download/akutz/generic/rexray-linux_amd64-0.2.0-rc2%2B20.tar.gz
Resolving bintray.com (bintray.com)... 108.168.194.90, 108.168.194.93
Connecting to bintray.com (bintray.com)|108.168.194.90|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dl.bintray.com/akutz/generic/rexray-linux_amd64-0.2.0-rc2+20.tar.gz [following]
--2015-09-15 00:02:47--  https://dl.bintray.com/akutz/generic/rexray-linux_amd64-0.2.0-rc2+20.tar.gz
Resolving dl.bintray.com (dl.bintray.com)... 108.168.194.91, 108.168.194.92
Connecting to dl.bintray.com (dl.bintray.com)|108.168.194.91|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4096707 (3.9M) [application/x-gzip]
Saving to: ‘rexray-linux_amd64-0.2.0-rc2+20.tar.gz’

100%[==========================================================>] 4,096,707   5.36MB/s   in 0.7s   

Last-modified header invalid -- time-stamp ignored.
2015-09-15 00:02:48 (5.36 MB/s) - ‘rexray-linux_amd64-0.2.0-rc2+20.tar.gz’ saved [4096707/4096707]

[0]akutz@ubuntu:~$ tar xzf rexray-linux_amd64-0.2.0-rc2+20.tar.gz 
[0]akutz@ubuntu:~$ ls
total 18M
drwxr-xr-x 4 akutz 4.0K Sep 15 00:02 ./
drwxr-xr-x 3 root  4.0K Aug 12 17:31 ../
-rw------- 1 akutz  25K Aug 18 12:46 .bash_history
-rw-r--r-- 1 akutz  220 Aug 12 17:31 .bash_logout
-rw-r--r-- 1 akutz 3.6K Aug 12 17:31 .bashrc.dist
drwx------ 2 akutz 4.0K Aug 12 17:41 .cache/
lrwxrwxrwx 1 akutz   13 Aug 12 17:47 go -> /media/psf/go/
-rw------- 1 akutz   42 Aug 12 19:16 .lesshst
-rw-r--r-- 1 akutz 1.2K Aug 12 18:19 .profile
-rwxr-xr-x 1 akutz  14M Sep 14 23:59 rexray*
-rw-rw-r-- 1 akutz 4.0M Sep 15 00:02 rexray-linux_amd64-0.2.0-rc2+20.tar.gz
drwx------ 2 akutz 4.0K Aug 12 17:53 .ssh/
-rw------- 1 akutz 4.7K Aug 17 12:57 .viminfo
[0]akutz@ubuntu:~$
```

```
[0]akutz@ubuntu:~$ sudo mv rexray /bin/
[sudo] password for akutz: 
[0]akutz@ubuntu:~$ sudo rexray service install
update-rc.d: warning: /etc/init.d/rexray missing LSB information
update-rc.d: see <http://wiki.debian.org/LSBInitScripts>
 System start/stop links for /etc/init.d/rexray already exist.
REX-Ray is now installed. Before starting it please check http://github.com/emccode/rexray for instructions on how to configure it.

 Once configured the REX-Ray service can be started with the command 'sudo /etc/init.d/rexray start'.

[0]akutz@ubuntu:~$ sudo /etc/init.d/rexray start
Oops, an error occured!

  no storage drivers initialized

To correct the error please review:

  - Debug output by using the flag -l debug
  - The REX-ray website at https://github.com/emccode/rexray
  - The on↓ine he↓p be↓ow

Start the service

Usage: 
  rexray service start [flags]

Flags:
      --client="": Socket the daemon uses to communicate to the client
  -f, --foreground[=false]: Starts the service in the foreground

Global Flags:
  -c, --config="/root/.rexray/config.yaml": The REX-Ray configuration file
  -?, --help[=false]: Help for start
  -h, --host="tcp://:7979": The REX-Ray service address
  -l, --logLevel="info": The log level (panic, fatal, error, warn, info, debug)
  -v, --verbose[=false]: Print verbose help information

[0]akutz@ubuntu:~$ 
```

**Comment by akutz** [comment] 2015-09-15 05:15
Hi @kacole2,

Your system likely has SELinux or some other security restrictions enabled on top of ACLs. That or the VM is provisioned with increased lockdowns in place. Your logs make zero sense unless you're specifically *trying* to break the program. If that's the case, bully for you, but let me know so I can put some guard in place. I'm not being sarcastic. I traced the logs, and one place it checks for the existence of a debug file, and if it exists it tries to read it. Well, you're in the inner logic, but that means the debug file would have to exist! On your system! That's nuts!

I don't know what's going on with it, but you'll have to do digging to figure it out.

**Comment by akutz** [comment] 2015-09-15 05:28
Hi @kacole2,

By the way, I did some digging of my own and verified that the `REX-Ray` function for checking if a file exists does not check a user's permission to read it, but that should be okay, because here's the thing. If the files `/etc/rexray/config.yaml` or `$HOME/.rexray/config.yaml` exist your user should *absolutely* be able to read them. The same for `$HOME/.rexray/usage.template`. First of all, why on earth you'd have that file in place is beyond me, but what's more likely is somehow you've got a system with screwed up permissions and you can't read `$HOME/.rexray` and it's throwing a permissions error. Here's the code FWIW:

```
func FileExists(filePath string) bool {
	if _, err := os.Stat(filePath); !os.IsNotExist(err) {
		return true
	}
	return false
}
```

The above will return a false-positive for files that don't exist at locations that you're prohibited from reading, but that's okay as it's not used for anything for which you shouldn't have read perms such as `/etc/rexray` and `$HOME/.rexray`.

**Comment by akutz** [comment] 2015-09-15 05:41
Hi @kacole2,

I've pushed a [patch](https://github.com/emccode/rexray/commit/52c6e199fff0d48c91714f6a59d9b4093fb9b49d) to handle the panics you're seeing. It institutes an access check as well as the existence check, but this is more about failing gracefully than solving the problem. The issue is that your system has permission restrictions that will keep `REX-ray` from ever working at all. You need to figure out why that is. I know you've had it running before, so did something happen to the system? Have you reprovisioned it lately? Any updates?

**Comment by clintonskitson** [comment] 2015-09-15 05:54
Hey @akutz, your error is showing that it tried to check if the `/etc/init.d/rexray` file was installed or not.  This isn't not the same test from @kacole2.  Try and remove that file and run the same command.

I have the same problem.. Found a fix..

If `/etc/init.d/rexray` doesn't exist you can put a `/bin/` prefix before rexray to make it work in the short term.  It looks like the path being linked to is based from the relative path of the process executing.

```
root@test14:~# sudo rexray service install
update-rc.d: /etc/init.d/rexray: file does not exist
FATA[0000] installation error exit status 1             
root@test14:~# sudo /bin/rexray service install
update-rc.d: /etc/init.d/rexray: file does not exist
FATA[0000] installation error exit status 1             
root@test14:~# ls /etc/init.d/rexray
/etc/init.d/rexray
root@test14:~# ls /etc/init.d/rexray -laF
lrwxrwxrwx 1 root root 12 Sep 15 01:52 /etc/init.d/rexray -> /root/rexray
root@test14:~# rm /etc/init.d/rexray
root@test14:~# sudo /bin/rexray service install
```

**Comment by akutz** [comment] 2015-09-15 06:00
Hi @clintonskitson,

I pasted the wrong log, but I removed that file as well and it still worked. Oh ye of little faith, I don't assert blindly :)

![image](https://cloud.githubusercontent.com/assets/101085/9869025/05a77d4e-5b45-11e5-8edc-41b08831322b.png)

I have no idea what you mean about the `/bin` prefix, but that's the directory to which he copied the file and it's perfectly the valid. The problem is his system has FUBAR permissions.

**Comment by clintonskitson** [comment] 2015-09-15 06:02
Look at my steps more clearly.. The system he is using is from the same
build as mine.  The /bin prefix makes it work correctly.

**Comment by clintonskitson** [comment] 2015-09-15 06:04
There is a link that gets created at first po bring to /root which makes no
sense since it does not exist there.

**Comment by clintonskitson** [comment] 2015-09-15 06:04
Sorry for typo, pointing to..

**Comment by akutz** [comment] 2015-09-15 06:08
Hi @clintonskitson,

I see what you mean, but I would have said something like:

`When creating a symlink to a file, if the file itself creates the symlink by taking its own execution path, then the full path must be given at time of execution else the file's execution path will be invalid as it could represent a relative path, or a path that expects to exist in the PATH variable scope which is what happened in this instance.`

This is easy enough to fix. I just released 0.2.0-rc2, so file an issue and I'll fix it for rc3. I don't want this to be the issue itself unless we can dismiss the rest of @kacole2's concerns.

**Comment by akutz** [comment] 2015-09-15 06:25
Hi @clintonskitson,

That's does not appear to be the issue as I double-checked, and I already get the abspath for the executing binary. See the following example with debug logging enable. Note I'm installing the service using a relative path:

```
[0]akutz@ubuntu:rexray$ sudo .bin/linux_amd64/rexray service install -l debug
DEBU[0000] updated log level                             logLevel=debug
DEBU[0000] creating symlink                              exeFile=/media/psf/go/src/github.com/emccode/rexray/.bin/linux_amd64/rexray initFile=/etc/init.d/rexray
update-rc.d: warning: /etc/init.d/rexray missing LSB information
update-rc.d: see <http://wiki.debian.org/LSBInitScripts>
 System start/stop links for /etc/init.d/rexray already exist.
REX-Ray is now installed. Before starting it please check http://github.com/emccode/rexray for instructions on how to configure it.

 Once configured the REX-Ray service can be started with the command 'sudo /etc/init.d/rexray start'.

[0]akutz@ubuntu:rexray$ ls /etc/init.d | grep rexray
lrwxrwxrwx  1 root   67 Sep 15 01:22 rexray -> /media/psf/go/src/github.com/emccode/rexray/.bin/linux_amd64/rexray*
[0]akutz@ubuntu:rexray$ 
```

If you'd like to look at the code, you can back track it from (here)[https://github.com/emccode/rexray/blob/master/rexray/commands/service.go#L383].

**Comment by akutz** [comment] 2015-09-15 06:36
Hi @clintonskitson,

Scratch that. It works as long as you give it any anchored path, relative or not. If however you rely on a path that is in the PATH variable it seems to simply take the parent directory and append "rexray" as the suffix. 

Found the (issue)[http://golang.org/pkg/path/filepath/#Abs]:

```
Abs returns an absolute representation of path. If the path is not absolute it will be joined with the current working directory to turn it into an absolute path. The absolute path name for a given file is not guaranteed to be unique.
```

The above is the stupidest thing I ever heard. Why join it with the current WD to turn it into an abs path when the nature of the function is to get the ABS PATH! DON'T GUESS! GET THE ABS PATH! *sigh*

Okay, I'll fix this bug.

**Comment by akutz** [comment] 2015-09-15 06:55
Hi @clintonskitson / @kacole2,

Thank you both for identifying and tracking down this bug. PR #56 is building for it right now, and I'll merge it as soon as the build succeeds.

**Comment by akutz** [comment] 2015-09-15 07:01
Hi @kacole2, 

[0.2.0-rc3+3](https://bintray.com/akutz/generic/rexray/0.2.0-rc3%2B3/view#files) has the patch.

**Closed by akutz** 2015-09-15 07:01 UTC

**Comment by kacole2** [comment] 2015-09-15 13:34
:+1: 
thanks. all working

```
Using SSH client type: external
About to run SSH command:
sudo rexray service start
&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=no -i /Users/kcoleman/.docker/machine/machines/fun21/id_rsa -p 22 ubuntu@54.236.246.3 sudo rexray service start] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
SSH cmd err, output: <nil>: Starting REX-Ray...SUCESS!

  The REX-Ray daemon is now running at PID 30433. To
  shutdown the daemon execute the following command:

    sudo /bin/rexray stop

```
